apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-frontend
  namespace: chat-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chat-frontend
  template:
    metadata:
      labels:
        app: chat-frontend
    spec:
      containers:
      - name: frontend
        image: 629649838083.dkr.ecr.us-east-1.amazonaws.com/chat-frontend:latest
        ports:
        - containerPort: 80
